// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fkwttklxbyivcawjbqwb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZrd3R0a2x4YnlpdmNhd2picXdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MDg5MzUsImV4cCI6MjA2NzQ4NDkzNX0.1OucZ1eeAjmT9_s-iwxbKqxcX8dCQgvNHanfkxgxhdE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});